### Register User
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name": "test",
  "email": "test@gmail.com",
  "password": "admin1234",
  "confirm": "admin1234"
}
 
###

GET http://localhost:3000/api/v1/products?id=store-1

###

GET http://localhost:3000/