-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "priceMin" DOUBLE PRECISION NOT NULL DEFAULT NULL,
ADD COLUMN     "sold" INTEGER NOT NULL DEFAULT NULL;

-- AlterTable
ALTER TABLE "Variant" ADD COLUMN     "sold" INTEGER NOT NULL DEFAULT 0;
